name: Build project

on: [push, pull_request]

jobs:
  
    steps:
        - uses: game-ci/unity-builder@v2
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            with:
            targetPlatform: StandaloneWindows 
        - uses: actions/upload-artifact@v2
            with:
            name: Build
            path: build

      