name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for StandaloneWindows 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.0-aplha-5
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2.0-aplha-5
        with:
          path: Library
          key: Library-StandaloneWindows 
          restore-keys: Library-
      - uses:  game-ci/unity-builder@v2.0-aplha-5
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows 
      - uses: actions/upload-artifact@v2.0-aplha-5
        with:
          name: Build-StandaloneWindows 
          path: build/StandaloneWindows 
